Console.ForegroundColor = ConsoleColor.Green;
Console.WriteLine("--> I'm printing green");
Console.ResetColor();
Console.ForegroundColor = ConsoleColor.Blue;
Console.WriteLine("--> I'm printing blue");
Console.ResetColor();
Console.ForegroundColor = ConsoleColor.Red;
Console.WriteLine("--> I'm printing red");
Console.ResetColor();
Console.ForegroundColor = ConsoleColor.Cyan;
Console.WriteLine("--> I'm printing cyan");
Console.ResetColor();